/* 
 * Rabbitmq Http API
 *
 * This is the OpenAPI specification of the RabbitMQ HTTP API. For more information, please refer to [HTTP API](https://cdn.rawgit.com/rabbitmq/rabbitmq-management/v3.7.14/priv/www/api/index.html) official documentation.
 *
 * OpenAPI spec version: 1.0
 * Contact: carlos@adaptive.me
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Thinkcode.RabbitMQ.OpenAPI.Client.OpenAPIDateConverter;

namespace Thinkcode.RabbitMQ.OpenAPI.Model
{
    /// <summary>
    /// BindingRequestArguments
    /// </summary>
    [DataContract]
    public partial class BindingRequestArguments :  IEquatable<BindingRequestArguments>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BindingRequestArguments" /> class.
        /// </summary>
        /// <param name="xArg">xArg.</param>
        public BindingRequestArguments(string xArg = default(string))
        {
            this.XArg = xArg;
        }
        
        /// <summary>
        /// Gets or Sets XArg
        /// </summary>
        [DataMember(Name="x-arg", EmitDefaultValue=false)]
        public string XArg { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BindingRequestArguments {\n");
            sb.Append("  XArg: ").Append(XArg).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BindingRequestArguments);
        }

        /// <summary>
        /// Returns true if BindingRequestArguments instances are equal
        /// </summary>
        /// <param name="input">Instance of BindingRequestArguments to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BindingRequestArguments input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.XArg == input.XArg ||
                    (this.XArg != null &&
                    this.XArg.Equals(input.XArg))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.XArg != null)
                    hashCode = hashCode * 59 + this.XArg.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
