/* 
 * Rabbitmq Http API
 *
 * This is the OpenAPI specification of the RabbitMQ HTTP API. For more information, please refer to [HTTP API](https://cdn.rawgit.com/rabbitmq/rabbitmq-management/v3.7.14/priv/www/api/index.html) official documentation.
 *
 * OpenAPI spec version: 1.0
 * Contact: carlos@adaptive.me
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Thinkcode.RabbitMQ.OpenAPI.Client.OpenAPIDateConverter;

namespace Thinkcode.RabbitMQ.OpenAPI.Model
{
    /// <summary>
    /// PublishResponse
    /// </summary>
    [DataContract]
    public partial class PublishResponse :  IEquatable<PublishResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PublishResponse" /> class.
        /// </summary>
        /// <param name="routed">routed.</param>
        public PublishResponse(bool routed = default(bool))
        {
            this.Routed = routed;
        }
        
        /// <summary>
        /// Gets or Sets Routed
        /// </summary>
        [DataMember(Name="routed", EmitDefaultValue=false)]
        public bool Routed { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PublishResponse {\n");
            sb.Append("  Routed: ").Append(Routed).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PublishResponse);
        }

        /// <summary>
        /// Returns true if PublishResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of PublishResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PublishResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Routed == input.Routed ||
                    (this.Routed != null &&
                    this.Routed.Equals(input.Routed))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Routed != null)
                    hashCode = hashCode * 59 + this.Routed.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
