/* 
 * Rabbitmq Http API
 *
 * This is the OpenAPI specification of the RabbitMQ HTTP API. For more information, please refer to [HTTP API](https://cdn.rawgit.com/rabbitmq/rabbitmq-management/v3.7.14/priv/www/api/index.html) official documentation.
 *
 * OpenAPI spec version: 1.0
 * Contact: carlos@adaptive.me
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Thinkcode.RabbitMQ.OpenAPI.Api;
using Thinkcode.RabbitMQ.OpenAPI.Model;
using Thinkcode.RabbitMQ.OpenAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Thinkcode.RabbitMQ.OpenAPI.Test
{
    /// <summary>
    ///  Class for testing BindingRequestArguments
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BindingRequestArgumentsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BindingRequestArguments
        //private BindingRequestArguments instance;

        public BindingRequestArgumentsTests()
        {
            // TODO uncomment below to create an instance of BindingRequestArguments
            //instance = new BindingRequestArguments();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BindingRequestArguments
        /// </summary>
        [Fact]
        public void BindingRequestArgumentsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BindingRequestArguments
            //Assert.IsInstanceOfType<BindingRequestArguments> (instance, "variable 'instance' is a BindingRequestArguments");
        }


        /// <summary>
        /// Test the property 'XArg'
        /// </summary>
        [Fact]
        public void XArgTest()
        {
            // TODO unit test for the property 'XArg'
        }

    }

}
