/* 
 * Rabbitmq Http API
 *
 * This is the OpenAPI specification of the RabbitMQ HTTP API. For more information, please refer to [HTTP API](https://cdn.rawgit.com/rabbitmq/rabbitmq-management/v3.7.14/priv/www/api/index.html) official documentation.
 *
 * OpenAPI spec version: 1.0
 * Contact: carlos@adaptive.me
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Thinkcode.RabbitMQ.OpenAPI.Api;
using Thinkcode.RabbitMQ.OpenAPI.Model;
using Thinkcode.RabbitMQ.OpenAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Thinkcode.RabbitMQ.OpenAPI.Test
{
    /// <summary>
    ///  Class for testing Definition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DefinitionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Definition
        //private Definition instance;

        public DefinitionTests()
        {
            // TODO uncomment below to create an instance of Definition
            //instance = new Definition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Definition
        /// </summary>
        [Fact]
        public void DefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Definition
            //Assert.IsInstanceOfType<Definition> (instance, "variable 'instance' is a Definition");
        }


        /// <summary>
        /// Test the property 'Bindings'
        /// </summary>
        [Fact]
        public void BindingsTest()
        {
            // TODO unit test for the property 'Bindings'
        }
        /// <summary>
        /// Test the property 'Exchanges'
        /// </summary>
        [Fact]
        public void ExchangesTest()
        {
            // TODO unit test for the property 'Exchanges'
        }
        /// <summary>
        /// Test the property 'Parameters'
        /// </summary>
        [Fact]
        public void ParametersTest()
        {
            // TODO unit test for the property 'Parameters'
        }
        /// <summary>
        /// Test the property 'Policies'
        /// </summary>
        [Fact]
        public void PoliciesTest()
        {
            // TODO unit test for the property 'Policies'
        }
        /// <summary>
        /// Test the property 'Queues'
        /// </summary>
        [Fact]
        public void QueuesTest()
        {
            // TODO unit test for the property 'Queues'
        }
        /// <summary>
        /// Test the property 'RabbitVersion'
        /// </summary>
        [Fact]
        public void RabbitVersionTest()
        {
            // TODO unit test for the property 'RabbitVersion'
        }

    }

}
