/* 
 * Rabbitmq Http API
 *
 * This is the OpenAPI specification of the RabbitMQ HTTP API. For more information, please refer to [HTTP API](https://cdn.rawgit.com/rabbitmq/rabbitmq-management/v3.7.14/priv/www/api/index.html) official documentation.
 *
 * OpenAPI spec version: 1.0
 * Contact: carlos@adaptive.me
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Thinkcode.RabbitMQ.OpenAPI.Api;
using Thinkcode.RabbitMQ.OpenAPI.Model;
using Thinkcode.RabbitMQ.OpenAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Thinkcode.RabbitMQ.OpenAPI.Test
{
    /// <summary>
    ///  Class for testing Exchange
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExchangeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Exchange
        //private Exchange instance;

        public ExchangeTests()
        {
            // TODO uncomment below to create an instance of Exchange
            //instance = new Exchange();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Exchange
        /// </summary>
        [Fact]
        public void ExchangeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Exchange
            //Assert.IsInstanceOfType<Exchange> (instance, "variable 'instance' is a Exchange");
        }


        /// <summary>
        /// Test the property 'Arguments'
        /// </summary>
        [Fact]
        public void ArgumentsTest()
        {
            // TODO unit test for the property 'Arguments'
        }
        /// <summary>
        /// Test the property 'AutoDelete'
        /// </summary>
        [Fact]
        public void AutoDeleteTest()
        {
            // TODO unit test for the property 'AutoDelete'
        }
        /// <summary>
        /// Test the property 'Durable'
        /// </summary>
        [Fact]
        public void DurableTest()
        {
            // TODO unit test for the property 'Durable'
        }
        /// <summary>
        /// Test the property 'Incoming'
        /// </summary>
        [Fact]
        public void IncomingTest()
        {
            // TODO unit test for the property 'Incoming'
        }
        /// <summary>
        /// Test the property 'Internal'
        /// </summary>
        [Fact]
        public void InternalTest()
        {
            // TODO unit test for the property 'Internal'
        }
        /// <summary>
        /// Test the property 'MessageStats'
        /// </summary>
        [Fact]
        public void MessageStatsTest()
        {
            // TODO unit test for the property 'MessageStats'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Outgoing'
        /// </summary>
        [Fact]
        public void OutgoingTest()
        {
            // TODO unit test for the property 'Outgoing'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'UserWhoPerformedAction'
        /// </summary>
        [Fact]
        public void UserWhoPerformedActionTest()
        {
            // TODO unit test for the property 'UserWhoPerformedAction'
        }
        /// <summary>
        /// Test the property 'Vhost'
        /// </summary>
        [Fact]
        public void VhostTest()
        {
            // TODO unit test for the property 'Vhost'
        }

    }

}
