/* 
 * Rabbitmq Http API
 *
 * This is the OpenAPI specification of the RabbitMQ HTTP API. For more information, please refer to [HTTP API](https://cdn.rawgit.com/rabbitmq/rabbitmq-management/v3.7.14/priv/www/api/index.html) official documentation.
 *
 * OpenAPI spec version: 1.0
 * Contact: carlos@adaptive.me
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Thinkcode.RabbitMQ.OpenAPI.Api;
using Thinkcode.RabbitMQ.OpenAPI.Model;
using Thinkcode.RabbitMQ.OpenAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Thinkcode.RabbitMQ.OpenAPI.Test
{
    /// <summary>
    ///  Class for testing ExchangeMessageStats
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExchangeMessageStatsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExchangeMessageStats
        //private ExchangeMessageStats instance;

        public ExchangeMessageStatsTests()
        {
            // TODO uncomment below to create an instance of ExchangeMessageStats
            //instance = new ExchangeMessageStats();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExchangeMessageStats
        /// </summary>
        [Fact]
        public void ExchangeMessageStatsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExchangeMessageStats
            //Assert.IsInstanceOfType<ExchangeMessageStats> (instance, "variable 'instance' is a ExchangeMessageStats");
        }


        /// <summary>
        /// Test the property 'PublishInDetails'
        /// </summary>
        [Fact]
        public void PublishInDetailsTest()
        {
            // TODO unit test for the property 'PublishInDetails'
        }
        /// <summary>
        /// Test the property 'PublishOutDetails'
        /// </summary>
        [Fact]
        public void PublishOutDetailsTest()
        {
            // TODO unit test for the property 'PublishOutDetails'
        }
        /// <summary>
        /// Test the property 'PublishIn'
        /// </summary>
        [Fact]
        public void PublishInTest()
        {
            // TODO unit test for the property 'PublishIn'
        }
        /// <summary>
        /// Test the property 'PublishOut'
        /// </summary>
        [Fact]
        public void PublishOutTest()
        {
            // TODO unit test for the property 'PublishOut'
        }

    }

}
