/* 
 * Rabbitmq Http API
 *
 * This is the OpenAPI specification of the RabbitMQ HTTP API. For more information, please refer to [HTTP API](https://cdn.rawgit.com/rabbitmq/rabbitmq-management/v3.7.14/priv/www/api/index.html) official documentation.
 *
 * OpenAPI spec version: 1.0
 * Contact: carlos@adaptive.me
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Thinkcode.RabbitMQ.OpenAPI.Api;
using Thinkcode.RabbitMQ.OpenAPI.Model;
using Thinkcode.RabbitMQ.OpenAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Thinkcode.RabbitMQ.OpenAPI.Test
{
    /// <summary>
    ///  Class for testing ExchangeRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExchangeRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExchangeRequest
        //private ExchangeRequest instance;

        public ExchangeRequestTests()
        {
            // TODO uncomment below to create an instance of ExchangeRequest
            //instance = new ExchangeRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExchangeRequest
        /// </summary>
        [Fact]
        public void ExchangeRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExchangeRequest
            //Assert.IsInstanceOfType<ExchangeRequest> (instance, "variable 'instance' is a ExchangeRequest");
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'AutoDelete'
        /// </summary>
        [Fact]
        public void AutoDeleteTest()
        {
            // TODO unit test for the property 'AutoDelete'
        }
        /// <summary>
        /// Test the property 'Durable'
        /// </summary>
        [Fact]
        public void DurableTest()
        {
            // TODO unit test for the property 'Durable'
        }
        /// <summary>
        /// Test the property 'Internal'
        /// </summary>
        [Fact]
        public void InternalTest()
        {
            // TODO unit test for the property 'Internal'
        }
        /// <summary>
        /// Test the property 'Arguments'
        /// </summary>
        [Fact]
        public void ArgumentsTest()
        {
            // TODO unit test for the property 'Arguments'
        }

    }

}
