/* 
 * Rabbitmq Http API
 *
 * This is the OpenAPI specification of the RabbitMQ HTTP API. For more information, please refer to [HTTP API](https://cdn.rawgit.com/rabbitmq/rabbitmq-management/v3.7.14/priv/www/api/index.html) official documentation.
 *
 * OpenAPI spec version: 1.0
 * Contact: carlos@adaptive.me
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Thinkcode.RabbitMQ.OpenAPI.Api;
using Thinkcode.RabbitMQ.OpenAPI.Model;
using Thinkcode.RabbitMQ.OpenAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Thinkcode.RabbitMQ.OpenAPI.Test
{
    /// <summary>
    ///  Class for testing OverviewObjectTotals
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OverviewObjectTotalsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OverviewObjectTotals
        //private OverviewObjectTotals instance;

        public OverviewObjectTotalsTests()
        {
            // TODO uncomment below to create an instance of OverviewObjectTotals
            //instance = new OverviewObjectTotals();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OverviewObjectTotals
        /// </summary>
        [Fact]
        public void OverviewObjectTotalsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OverviewObjectTotals
            //Assert.IsInstanceOfType<OverviewObjectTotals> (instance, "variable 'instance' is a OverviewObjectTotals");
        }


        /// <summary>
        /// Test the property 'Channels'
        /// </summary>
        [Fact]
        public void ChannelsTest()
        {
            // TODO unit test for the property 'Channels'
        }
        /// <summary>
        /// Test the property 'Queues'
        /// </summary>
        [Fact]
        public void QueuesTest()
        {
            // TODO unit test for the property 'Queues'
        }
        /// <summary>
        /// Test the property 'Exchanges'
        /// </summary>
        [Fact]
        public void ExchangesTest()
        {
            // TODO unit test for the property 'Exchanges'
        }
        /// <summary>
        /// Test the property 'Consumers'
        /// </summary>
        [Fact]
        public void ConsumersTest()
        {
            // TODO unit test for the property 'Consumers'
        }
        /// <summary>
        /// Test the property 'Connections'
        /// </summary>
        [Fact]
        public void ConnectionsTest()
        {
            // TODO unit test for the property 'Connections'
        }

    }

}
