/* 
 * Rabbitmq Http API
 *
 * This is the OpenAPI specification of the RabbitMQ HTTP API. For more information, please refer to [HTTP API](https://cdn.rawgit.com/rabbitmq/rabbitmq-management/v3.7.14/priv/www/api/index.html) official documentation.
 *
 * OpenAPI spec version: 1.0
 * Contact: carlos@adaptive.me
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Thinkcode.RabbitMQ.OpenAPI.Api;
using Thinkcode.RabbitMQ.OpenAPI.Model;
using Thinkcode.RabbitMQ.OpenAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Thinkcode.RabbitMQ.OpenAPI.Test
{
    /// <summary>
    ///  Class for testing OverviewExchangeTypes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OverviewExchangeTypesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OverviewExchangeTypes
        //private OverviewExchangeTypes instance;

        public OverviewExchangeTypesTests()
        {
            // TODO uncomment below to create an instance of OverviewExchangeTypes
            //instance = new OverviewExchangeTypes();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OverviewExchangeTypes
        /// </summary>
        [Fact]
        public void OverviewExchangeTypesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OverviewExchangeTypes
            //Assert.IsInstanceOfType<OverviewExchangeTypes> (instance, "variable 'instance' is a OverviewExchangeTypes");
        }


        /// <summary>
        /// Test the property 'InternalPurpose'
        /// </summary>
        [Fact]
        public void InternalPurposeTest()
        {
            // TODO unit test for the property 'InternalPurpose'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

    }

}
