/* 
 * Rabbitmq Http API
 *
 * This is the OpenAPI specification of the RabbitMQ HTTP API. For more information, please refer to [HTTP API](https://cdn.rawgit.com/rabbitmq/rabbitmq-management/v3.7.14/priv/www/api/index.html) official documentation.
 *
 * OpenAPI spec version: 1.0
 * Contact: carlos@adaptive.me
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Thinkcode.RabbitMQ.OpenAPI.Api;
using Thinkcode.RabbitMQ.OpenAPI.Model;
using Thinkcode.RabbitMQ.OpenAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Thinkcode.RabbitMQ.OpenAPI.Test
{
    /// <summary>
    ///  Class for testing OverviewChurnRates
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OverviewChurnRatesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OverviewChurnRates
        //private OverviewChurnRates instance;

        public OverviewChurnRatesTests()
        {
            // TODO uncomment below to create an instance of OverviewChurnRates
            //instance = new OverviewChurnRates();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OverviewChurnRates
        /// </summary>
        [Fact]
        public void OverviewChurnRatesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OverviewChurnRates
            //Assert.IsInstanceOfType<OverviewChurnRates> (instance, "variable 'instance' is a OverviewChurnRates");
        }


        /// <summary>
        /// Test the property 'QueueDeleted'
        /// </summary>
        [Fact]
        public void QueueDeletedTest()
        {
            // TODO unit test for the property 'QueueDeleted'
        }
        /// <summary>
        /// Test the property 'ChannelCreatedDetails'
        /// </summary>
        [Fact]
        public void ChannelCreatedDetailsTest()
        {
            // TODO unit test for the property 'ChannelCreatedDetails'
        }
        /// <summary>
        /// Test the property 'ChannelCreated'
        /// </summary>
        [Fact]
        public void ChannelCreatedTest()
        {
            // TODO unit test for the property 'ChannelCreated'
        }
        /// <summary>
        /// Test the property 'ChannelClosed'
        /// </summary>
        [Fact]
        public void ChannelClosedTest()
        {
            // TODO unit test for the property 'ChannelClosed'
        }
        /// <summary>
        /// Test the property 'QueueDeclaredDetails'
        /// </summary>
        [Fact]
        public void QueueDeclaredDetailsTest()
        {
            // TODO unit test for the property 'QueueDeclaredDetails'
        }
        /// <summary>
        /// Test the property 'ConnectionClosed'
        /// </summary>
        [Fact]
        public void ConnectionClosedTest()
        {
            // TODO unit test for the property 'ConnectionClosed'
        }
        /// <summary>
        /// Test the property 'ChannelClosedDetails'
        /// </summary>
        [Fact]
        public void ChannelClosedDetailsTest()
        {
            // TODO unit test for the property 'ChannelClosedDetails'
        }
        /// <summary>
        /// Test the property 'QueueCreated'
        /// </summary>
        [Fact]
        public void QueueCreatedTest()
        {
            // TODO unit test for the property 'QueueCreated'
        }
        /// <summary>
        /// Test the property 'QueueDeclared'
        /// </summary>
        [Fact]
        public void QueueDeclaredTest()
        {
            // TODO unit test for the property 'QueueDeclared'
        }
        /// <summary>
        /// Test the property 'ConnectionClosedDetails'
        /// </summary>
        [Fact]
        public void ConnectionClosedDetailsTest()
        {
            // TODO unit test for the property 'ConnectionClosedDetails'
        }
        /// <summary>
        /// Test the property 'QueueDeletedDetails'
        /// </summary>
        [Fact]
        public void QueueDeletedDetailsTest()
        {
            // TODO unit test for the property 'QueueDeletedDetails'
        }
        /// <summary>
        /// Test the property 'ConnectionCreated'
        /// </summary>
        [Fact]
        public void ConnectionCreatedTest()
        {
            // TODO unit test for the property 'ConnectionCreated'
        }
        /// <summary>
        /// Test the property 'ConnectionCreatedDetails'
        /// </summary>
        [Fact]
        public void ConnectionCreatedDetailsTest()
        {
            // TODO unit test for the property 'ConnectionCreatedDetails'
        }
        /// <summary>
        /// Test the property 'QueueCreatedDetails'
        /// </summary>
        [Fact]
        public void QueueCreatedDetailsTest()
        {
            // TODO unit test for the property 'QueueCreatedDetails'
        }

    }

}
