/* 
 * Rabbitmq Http API
 *
 * This is the OpenAPI specification of the RabbitMQ HTTP API. For more information, please refer to [HTTP API](https://cdn.rawgit.com/rabbitmq/rabbitmq-management/v3.7.14/priv/www/api/index.html) official documentation.
 *
 * OpenAPI spec version: 1.0
 * Contact: carlos@adaptive.me
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Thinkcode.RabbitMQ.OpenAPI.Api;
using Thinkcode.RabbitMQ.OpenAPI.Model;
using Thinkcode.RabbitMQ.OpenAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Thinkcode.RabbitMQ.OpenAPI.Test
{
    /// <summary>
    ///  Class for testing OverviewSampleRetentionPolicies
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OverviewSampleRetentionPoliciesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OverviewSampleRetentionPolicies
        //private OverviewSampleRetentionPolicies instance;

        public OverviewSampleRetentionPoliciesTests()
        {
            // TODO uncomment below to create an instance of OverviewSampleRetentionPolicies
            //instance = new OverviewSampleRetentionPolicies();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OverviewSampleRetentionPolicies
        /// </summary>
        [Fact]
        public void OverviewSampleRetentionPoliciesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OverviewSampleRetentionPolicies
            //Assert.IsInstanceOfType<OverviewSampleRetentionPolicies> (instance, "variable 'instance' is a OverviewSampleRetentionPolicies");
        }


        /// <summary>
        /// Test the property 'Detailed'
        /// </summary>
        [Fact]
        public void DetailedTest()
        {
            // TODO unit test for the property 'Detailed'
        }
        /// <summary>
        /// Test the property 'Global'
        /// </summary>
        [Fact]
        public void GlobalTest()
        {
            // TODO unit test for the property 'Global'
        }
        /// <summary>
        /// Test the property 'Basic'
        /// </summary>
        [Fact]
        public void BasicTest()
        {
            // TODO unit test for the property 'Basic'
        }

    }

}
