/* 
 * Rabbitmq Http API
 *
 * This is the OpenAPI specification of the RabbitMQ HTTP API. For more information, please refer to [HTTP API](https://cdn.rawgit.com/rabbitmq/rabbitmq-management/v3.7.14/priv/www/api/index.html) official documentation.
 *
 * OpenAPI spec version: 1.0
 * Contact: carlos@adaptive.me
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Thinkcode.RabbitMQ.OpenAPI.Api;
using Thinkcode.RabbitMQ.OpenAPI.Model;
using Thinkcode.RabbitMQ.OpenAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Thinkcode.RabbitMQ.OpenAPI.Test
{
    /// <summary>
    ///  Class for testing QueueBackingQueueStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QueueBackingQueueStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for QueueBackingQueueStatus
        //private QueueBackingQueueStatus instance;

        public QueueBackingQueueStatusTests()
        {
            // TODO uncomment below to create an instance of QueueBackingQueueStatus
            //instance = new QueueBackingQueueStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QueueBackingQueueStatus
        /// </summary>
        [Fact]
        public void QueueBackingQueueStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" QueueBackingQueueStatus
            //Assert.IsInstanceOfType<QueueBackingQueueStatus> (instance, "variable 'instance' is a QueueBackingQueueStatus");
        }


        /// <summary>
        /// Test the property 'Q1'
        /// </summary>
        [Fact]
        public void Q1Test()
        {
            // TODO unit test for the property 'Q1'
        }
        /// <summary>
        /// Test the property 'Q2'
        /// </summary>
        [Fact]
        public void Q2Test()
        {
            // TODO unit test for the property 'Q2'
        }
        /// <summary>
        /// Test the property 'Q3'
        /// </summary>
        [Fact]
        public void Q3Test()
        {
            // TODO unit test for the property 'Q3'
        }
        /// <summary>
        /// Test the property 'Q4'
        /// </summary>
        [Fact]
        public void Q4Test()
        {
            // TODO unit test for the property 'Q4'
        }
        /// <summary>
        /// Test the property 'TargetRamCount'
        /// </summary>
        [Fact]
        public void TargetRamCountTest()
        {
            // TODO unit test for the property 'TargetRamCount'
        }
        /// <summary>
        /// Test the property 'Delta'
        /// </summary>
        [Fact]
        public void DeltaTest()
        {
            // TODO unit test for the property 'Delta'
        }
        /// <summary>
        /// Test the property 'NextSeqId'
        /// </summary>
        [Fact]
        public void NextSeqIdTest()
        {
            // TODO unit test for the property 'NextSeqId'
        }
        /// <summary>
        /// Test the property 'AvgIngressRate'
        /// </summary>
        [Fact]
        public void AvgIngressRateTest()
        {
            // TODO unit test for the property 'AvgIngressRate'
        }
        /// <summary>
        /// Test the property 'AvgAckIngressRate'
        /// </summary>
        [Fact]
        public void AvgAckIngressRateTest()
        {
            // TODO unit test for the property 'AvgAckIngressRate'
        }
        /// <summary>
        /// Test the property 'AvgEgressRate'
        /// </summary>
        [Fact]
        public void AvgEgressRateTest()
        {
            // TODO unit test for the property 'AvgEgressRate'
        }
        /// <summary>
        /// Test the property 'Mode'
        /// </summary>
        [Fact]
        public void ModeTest()
        {
            // TODO unit test for the property 'Mode'
        }
        /// <summary>
        /// Test the property 'Len'
        /// </summary>
        [Fact]
        public void LenTest()
        {
            // TODO unit test for the property 'Len'
        }
        /// <summary>
        /// Test the property 'AvgAckEgressRate'
        /// </summary>
        [Fact]
        public void AvgAckEgressRateTest()
        {
            // TODO unit test for the property 'AvgAckEgressRate'
        }

    }

}
