/* 
 * Rabbitmq Http API
 *
 * This is the OpenAPI specification of the RabbitMQ HTTP API. For more information, please refer to [HTTP API](https://cdn.rawgit.com/rabbitmq/rabbitmq-management/v3.7.14/priv/www/api/index.html) official documentation.
 *
 * OpenAPI spec version: 1.0
 * Contact: carlos@adaptive.me
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Thinkcode.RabbitMQ.OpenAPI.Api;
using Thinkcode.RabbitMQ.OpenAPI.Model;
using Thinkcode.RabbitMQ.OpenAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Thinkcode.RabbitMQ.OpenAPI.Test
{
    /// <summary>
    ///  Class for testing VHostRecvOctDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VHostRecvOctDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VHostRecvOctDetails
        //private VHostRecvOctDetails instance;

        public VHostRecvOctDetailsTests()
        {
            // TODO uncomment below to create an instance of VHostRecvOctDetails
            //instance = new VHostRecvOctDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VHostRecvOctDetails
        /// </summary>
        [Fact]
        public void VHostRecvOctDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VHostRecvOctDetails
            //Assert.IsInstanceOfType<VHostRecvOctDetails> (instance, "variable 'instance' is a VHostRecvOctDetails");
        }


        /// <summary>
        /// Test the property 'Rate'
        /// </summary>
        [Fact]
        public void RateTest()
        {
            // TODO unit test for the property 'Rate'
        }

    }

}
